import { build, transform } from 'esbuild'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const appDirectory = resolve(repositoryRoot, 'src/adapters/mcp/app')
const templatePath = resolve(appDirectory, 'index.html')
const entryPath = resolve(appDirectory, 'view.ts')
const outputPath = resolve(repositoryRoot, 'src/adapters/mcp/app.generated.ts')

const result = await build({
  entryPoints: [entryPath],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2022'],
  minify: true,
  legalComments: 'none',
  sourcemap: false,
  write: false,
  outdir: 'mcp-app-build',
})

const javascript = result.outputFiles.find((file) => file.path.endsWith('.js'))?.text
const css = result.outputFiles.find((file) => file.path.endsWith('.css'))?.text
if (!javascript || !css) throw new Error('MCP App build did not emit both JavaScript and CSS')
new Function(javascript)

const template = await readFile(templatePath, 'utf8')
if (!template.includes('/* ABLE_APP_STYLES */') || !template.includes('/* ABLE_APP_SCRIPT */')) {
  throw new Error('MCP App HTML template placeholders are missing')
}
const embeddedJavascript = javascript.replaceAll('</script', '<\\/script')
await transform(embeddedJavascript, { loader: 'js' })
const html = template
  .replace('/* ABLE_APP_STYLES */', () => css.replaceAll('</style', '<\\/style'))
  .replace('/* ABLE_APP_SCRIPT */', () => embeddedJavascript)

const generated = [
  '// Generated by scripts/build-mcp-app.mjs. Do not edit directly.',
  `export const MCP_APP_HTML = ${JSON.stringify(html)}`,
  '',
].join('\n')

await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, generated, 'utf8')
