import { env } from 'cloudflare:workers'
import { applyD1Migrations } from 'cloudflare:test'
import { beforeEach } from 'vitest'

await applyD1Migrations(env.DB, env.TEST_MIGRATIONS as Array<{ name: string; queries: string[] }>)

beforeEach(async () => {
  await env.DB.batch([
    env.DB.prepare('DROP TRIGGER IF EXISTS audit_events_immutable_update'),
    env.DB.prepare('DROP TRIGGER IF EXISTS audit_events_immutable_delete'),
    env.DB.prepare('DROP TRIGGER IF EXISTS operation_receipts_immutable_update'),
    env.DB.prepare('DROP TRIGGER IF EXISTS operation_receipts_immutable_delete'),
    env.DB.prepare('DROP TRIGGER IF EXISTS directory_external_links_immutable_update'),
    env.DB.prepare('DROP TRIGGER IF EXISTS directory_external_links_immutable_delete'),
    env.DB.prepare('DROP TRIGGER IF EXISTS operation_outcome_observations_immutable_update'),
    env.DB.prepare('DROP TRIGGER IF EXISTS operation_outcome_observations_immutable_delete'),
    env.DB.prepare('DROP TRIGGER IF EXISTS improvement_evaluations_immutable_update'),
    env.DB.prepare('DROP TRIGGER IF EXISTS improvement_evaluations_immutable_delete'),
    env.DB.prepare('DELETE FROM outbox_rows'),
    env.DB.prepare('DELETE FROM communication_provider_delivery_events'),
    env.DB.prepare('DELETE FROM communication_provider_events'),
    env.DB.prepare('DELETE FROM communication_routes'),
    env.DB.prepare('DELETE FROM communication_messages'),
    env.DB.prepare('DELETE FROM communication_conversations'),
    env.DB.prepare('DELETE FROM voice_ticket_events'),
    env.DB.prepare('DELETE FROM helpdesk_case_sources'),
    env.DB.prepare('DELETE FROM case_attachments'),
    env.DB.prepare('DELETE FROM kb_article_attachments'),
    env.DB.prepare('DELETE FROM file_intelligence'),
    env.DB.prepare('DELETE FROM stored_files'),
    env.DB.prepare('DELETE FROM messages'),
    env.DB.prepare('DELETE FROM audit_events'),
    env.DB.prepare('DELETE FROM operation_outcome_observations'),
    env.DB.prepare('DELETE FROM operation_closures'),
    env.DB.prepare('DELETE FROM improvement_evaluations'),
    env.DB.prepare('DELETE FROM improvement_proposals'),
    env.DB.prepare('DELETE FROM operation_receipts'),
    env.DB.prepare('DELETE FROM crm_followups'),
    env.DB.prepare('DELETE FROM crm_activities'),
    env.DB.prepare('DELETE FROM crm_sales_leads'),
    env.DB.prepare('DELETE FROM crm_relationships'),
    env.DB.prepare('DELETE FROM directory_external_links'),
    env.DB.prepare('DELETE FROM directory_contact_points'),
    env.DB.prepare('DELETE FROM directory_parties'),
    env.DB.prepare('DELETE FROM external_provenance'),
    env.DB.prepare('DELETE FROM cases'),
    env.DB.prepare('DELETE FROM customers'),
    env.DB.prepare('DELETE FROM operators'),
    env.DB.prepare('DELETE FROM kb_articles'),
    env.DB.prepare('DELETE FROM kb_sections'),
    env.DB.prepare("DELETE FROM sqlite_sequence WHERE name = 'cases'"),
    env.DB.prepare(`UPDATE email_notification_templates SET enabled = 1,
      subject_template = 'We received [{{case_ref}}]: {{case_subject}}',
      body_text_template = 'Hi {{customer_name}},\n\nWe received your request {{case_ref}}.\n\nOpen your private case: {{case_link}}\n\nIf the link is unavailable, request a fresh link: {{recovery_link}}\n\n— {{workspace_name}} Support',
      body_markdown_template = 'Hi {{customer_name}},\n\n## We received your request\n\nReference: **{{case_ref}}**\n\n[Open your private case]({{case_link}})\n\nIf the link is unavailable, [request a fresh link]({{recovery_link}}).\n\n— {{workspace_name}} Support',
      updated_at = CURRENT_TIMESTAMP WHERE notification = 'case_received'`),
    env.DB.prepare(`UPDATE email_notification_templates SET enabled = 1,
      subject_template = 'Update received [{{case_ref}}]: {{case_subject}}',
      body_text_template = 'Hi {{customer_name}},\n\nWe added your update to {{case_ref}}.\n\nView your private case: {{case_link}}\n\nRecover the link: {{recovery_link}}\n\n— {{workspace_name}} Support',
      body_markdown_template = 'Hi {{customer_name}},\n\n## Your update was received\n\nWe added it to **{{case_ref}}**.\n\n[View your private case]({{case_link}})\n\n[Recover the link]({{recovery_link}})\n\n— {{workspace_name}} Support',
      updated_at = CURRENT_TIMESTAMP WHERE notification = 'customer_update_received'`),
    env.DB.prepare(`UPDATE email_notification_templates SET enabled = 1,
      subject_template = 'Re: [{{case_ref}}] {{case_subject}}',
      body_text_template = 'Hi {{customer_name}},\n\n{{message_body}}\n\nView your private case: {{case_link}}\n\nRecover the link: {{recovery_link}}\n\n— {{workspace_name}} Support',
      body_markdown_template = 'Hi {{customer_name}},\n\n{{message_body}}\n\n[View your private case]({{case_link}})\n\n[Recover the link]({{recovery_link}})\n\n— {{workspace_name}} Support',
      updated_at = CURRENT_TIMESTAMP WHERE notification = 'agent_reply'`),
    env.DB.prepare(`UPDATE email_notification_templates SET enabled = 1,
      subject_template = 'Private link for {{case_ref}}',
      body_text_template = 'Hi {{customer_name}},\n\nOpen your private case: {{case_link}}\n\n— {{workspace_name}} Support',
      body_markdown_template = 'Hi {{customer_name}},\n\n## Your fresh private link\n\n[Open your private case]({{case_link}})\n\n— {{workspace_name}} Support',
      updated_at = CURRENT_TIMESTAMP WHERE notification = 'case_recovery'`),
    env.DB.prepare(`UPDATE workspace_settings SET
      display_name = 'Morrow Desk', portal_title = 'How can we help?', logo_url = NULL, favicon_url = NULL,
      home_url = NULL, support_email = NULL, outbound_sender = NULL, case_prefix = 'MD',
      locale = 'en', timezone = 'UTC', support_hours_json = '{}', accent_color = '#b54a28',
      canvas_color = '#f5f2ec', ink_color = '#191918', font_family = 'system',
      portal_base_url = NULL, public_intake_enabled = 0, email_tested_at = NULL,
      setup_completed_at = NULL, updated_at = CURRENT_TIMESTAMP
    WHERE id = 1`),
    env.DB.prepare("CREATE TRIGGER audit_events_immutable_update BEFORE UPDATE ON audit_events BEGIN SELECT RAISE(ABORT, 'audit events are immutable'); END"),
    env.DB.prepare("CREATE TRIGGER audit_events_immutable_delete BEFORE DELETE ON audit_events BEGIN SELECT RAISE(ABORT, 'audit events are immutable'); END"),
    env.DB.prepare("CREATE TRIGGER operation_receipts_immutable_update BEFORE UPDATE ON operation_receipts BEGIN SELECT RAISE(ABORT, 'operation receipts are immutable'); END"),
    env.DB.prepare("CREATE TRIGGER operation_receipts_immutable_delete BEFORE DELETE ON operation_receipts BEGIN SELECT RAISE(ABORT, 'operation receipts are immutable'); END"),
    env.DB.prepare("CREATE TRIGGER directory_external_links_immutable_update BEFORE UPDATE ON directory_external_links BEGIN SELECT RAISE(ABORT, 'directory external links are immutable'); END"),
    env.DB.prepare("CREATE TRIGGER directory_external_links_immutable_delete BEFORE DELETE ON directory_external_links BEGIN SELECT RAISE(ABORT, 'directory external links are immutable'); END"),
    env.DB.prepare("CREATE TRIGGER operation_outcome_observations_immutable_update BEFORE UPDATE ON operation_outcome_observations BEGIN SELECT RAISE(ABORT, 'operation outcome observations are immutable'); END"),
    env.DB.prepare("CREATE TRIGGER operation_outcome_observations_immutable_delete BEFORE DELETE ON operation_outcome_observations BEGIN SELECT RAISE(ABORT, 'operation outcome observations are immutable'); END"),
    env.DB.prepare("CREATE TRIGGER improvement_evaluations_immutable_update BEFORE UPDATE ON improvement_evaluations BEGIN SELECT RAISE(ABORT, 'improvement evaluations are immutable'); END"),
    env.DB.prepare("CREATE TRIGGER improvement_evaluations_immutable_delete BEFORE DELETE ON improvement_evaluations BEGIN SELECT RAISE(ABORT, 'improvement evaluations are immutable'); END"),
    env.DB.prepare(`UPDATE loop_controls SET runtime_frozen = 0, tenant_adaptation_frozen = 1,
      product_improvement_frozen = 1, updated_by = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = 1`),
  ])
  let cursor: string | undefined
  do {
    const listed = await env.ATTACHMENTS.list(cursor ? { cursor } : {})
    if (listed.objects.length) await env.ATTACHMENTS.delete(listed.objects.map((object) => object.key))
    cursor = listed.truncated ? listed.cursor : undefined
  } while (cursor)
})
